---
# list of applications to install
local_home: "{{ lookup('env','HOME') }}"
work_dir: "{{ local_home }}/Work"

# homebrew applications
applications:
  # shell utils
  - autojump
  - zsh
  - tree
  - httpie
  - curl
  - wget
  - ctags
  - tmux
  - ag
  - fzf
  - git
  - git-lfs
  - tig
  - watch

  # editor
  - vim
  - neovim

  # lang
  - go
  - dep
  - rbenv
  - pyenv
  - pyenv-virtualenv
  - nvm

  # elm stuff
  - elm
  - elm-format

  # dependencies
  #- postgresql
  #- qt5
  #- imagemagick

  # tools
  #- phraseapp
  #- circleci

# homebrew cask applications
cask_applications:
  #- phantomjs
  - google-chrome
  - firefox-developer-edition
  #- slack
  - iterm2
  - docker
  - emacs
  - 1password
  - spotify
  - sublime-text
  - spectacle
  #- skype
  #- java
  - visual-studio-code
  - evernote

cask_fonts:
  - font-inconsolata
  - font-inconsolata-g-for-powerline
  - font-fira-mono
  - font-fira-mono-for-powerline
  - font-fira-code
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-fontawesome
  - font-materialdesignicons-webfont
  - font-hack
  - font-meslo-lg
  - font-meslo-for-powerline
  - font-dejavusansmono-nerd-font
  - font-dejavu-sans-mono-for-powerline

go_libs:
  - github.com/nsf/gocode
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  - golang.org/x/tools/cmd/gorename
  - golang.org/x/tools/cmd/goimports
