---
# list of applications to install
local_home: "{{ lookup('env','HOME') }}"
work_dir: "{{ local_home }}/Work"

# homebrew applications
applications:
  # shell utils
  - autojump
  - zsh
  - tree
  - httpie
  - curl
  - wget
  - ctags
  - tmux
  - ag
  - fzf
  - git
  - git-lfs
  - tig

  # editor
  - vim
  - neovim

  # lang
  - go
  - rbenv
  - pyenv
  - pyenv-virtualenv

# homebrew cask applications
cask_applications:
  - google-chrome
  - firefoxdeveloperedition
  - slack
  - iterm2
  - docker
  - emacs
  - 1password
  - spotify
  - sublime-text
  - spectacle
  - karabiner

cask_fonts:
  - font-inconsolata
  - font-inconsolata-g-for-powerline
  - font-fira-mono
  - font-fira-mono-for-powerline
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-fontawesome
  - font-materialdesignicons-webfont
  - font-hack

downloads:
   zwift:
     name: Zwift
     url: http://cdn.zwift.com/app/ZwiftOSX.dmg
     dest: "{{local_home}}/Downloads/ZwiftOSX.dmg"
   suuntolink:
     name: Suunto Movescount link
     url: http://suuntolink.static.movescount.com/Suuntolink_installer.dmg
     dest: "{{local_home}}/Downloads/Suuntolink_installer.dmg"
