---
# getting my dotfile configuration

- name: spacemacs dot file
  copy:
    src: dotfiles/spacemacs
    dest: "{{local_home}}/.spacemacs"

- name: tmux dot file
  copy:
    src: dotfiles/tmux.conf
    dest: "{{local_home}}/.tmux.conf"
